# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Grubbs' Test
#'
#' @param y NumericVector
#' @param n IntegerVector
#' @param alpha double
#' @export
grubbs_test_cpp <- function(y, n, alpha) {
    .Call('outlierDetection_grubbs_test_cpp', PACKAGE = 'outlierDetection', y, n, alpha)
}

#' Sequential Grubbs' Tests
#'
#' @param in_vector NumericVector
#' @param max_outlier_pct double
#' @param alpha double
#' @export
sequential_grubbs_test_cpp <- function(in_vector, max_outlier_pct, alpha) {
    .Call('outlierDetection_sequential_grubbs_test_cpp', PACKAGE = 'outlierDetection', in_vector, max_outlier_pct, alpha)
}

#' Sequential Grubbs' Tests Df
#'
#' @param df DataFrame
#' @param var_in string
#' @param var_out string
#' @param max_outlier_pct double
#' @param alpha double
#' @export
sequential_grubbs_test_cpp_df <- function(df, var_in, var_out, max_outlier_pct, alpha) {
    .Call('outlierDetection_sequential_grubbs_test_cpp_df', PACKAGE = 'outlierDetection', df, var_in, var_out, max_outlier_pct, alpha)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('outlierDetection_RcppExport_registerCCallable', PACKAGE = 'outlierDetection')
})
